-- SQLite

INSERT INTO TABELA_CURSO (
  NOME,
  ID_CATEGORIA_CURSO,
  CURSO_SLUG,
  IMG_URL
)
VALUES 
('Técnico em Desenvolvimento de Software', 1, 'desenvolvimento-de-software', 'https://i.postimg.cc/Typ0295J/T-cnico-em-Desenvolvimento-de-Software.png'),
('Técnico em Suporte de Informática', 1, 'suporte-de-informatica', 'https://i.postimg.cc/cgtFhmsL/T-cnico-em-Suporte-de-Inform-tica.png'),
('Curso de Programação Web', 1, 'programacao-web', 'https://i.postimg.cc/wtvfyzZJ/Curso-de-Programa-o-Web.png'),
('Curso de Segurança da Informação', 1, 'seguranca-da-informacao', 'https://i.postimg.cc/PPjSbY0d/Curso-de-Seguran-a-da-Informa-o.png'),
('Curso de Análise de Dados', 1, 'analise-de-dados', 'https://i.postimg.cc/VSgw1zMC/Curso-de-Analise-de-Dados.png'),
('Curso de Design de Interface de Usuário', 1, 'design-de-interface-de-usuario', 'https://i.postimg.cc/G9HRwwp4/Curso-de-Design-de-Interface-de-Usu-rio.png'),
('Curso de Administração de Banco de Dados', 1, 'administracao-de-banco-de-dados', 'https://i.postimg.cc/06PvLz6v/Curso-de-Administra-o-de-Banco-de-Dados.png'),
('Curso de Redes de Computadores', 1, 'redes-de-computadores', 'https://i.postimg.cc/8sWyrtKy/Curso-de-Redes-de-Computadores.png'),
('Técnico em Administração de Empresas', 2, 'administracao-de-empresas', 'https://i.postimg.cc/xXsgS78d/T-cnico-em-Administra-o-de-Empresas.png'),
('Técnico em Gestão Financeira', 2, 'gestao-financeira', 'https://i.postimg.cc/YGFxYC34/T-cnico-em-Gest-o-Financeira.png'),
('Curso de Marketing Digital', 2, 'marketing-digital', 'https://i.postimg.cc/HVDhSf8D/Curso-de-Marketing-Digital.png'),
('Curso de Gestão de Projetos', 2, 'gestao-de-projetos', 'https://i.postimg.cc/5XmTQn0c/Curso-de-Gest-o-de-Projetos.png'),
('Curso de Recursos Humanos', 2, 'recursos-humanos', 'https://i.postimg.cc/XBMQzCJc/Curso-de-Recursos-Humanos.png'),
('Curso de Empreendedorismo', 2, 'empreendorismo', 'https://i.postimg.cc/ygGwYxNk/Curso-de-Empreendedorismo.png'),
('Curso de Logística Empresarial', 2, 'logistica-empresarial', 'https://i.postimg.cc/0MhB14tS/Curso-de-Log-stica-Empresarial.png'),
('Curso de Contabilidade Básica', 2, 'cotabilidade-basica', 'https://i.postimg.cc/GT8nkYfF/Curso-de-Contabilidade-B-sica.png'),
('Técnico em Enfermagem', 3, 'enfermagem', 'https://i.postimg.cc/zL6jygnZ/T-cnico-em-Enfermagem.png'),
('Técnico em Radiologia', 3, 'radiologia', 'https://i.postimg.cc/JHW5qC6p/T-cnico-em-Radiologia.png'),
('Curso de Primeiros Socorros', 3, 'primeiros-socorros' , 'https://i.postimg.cc/3k9fxNSY/Curso-de-Primeiros-Socorros.png'),
('Curso de Massoterapia', 3, 'massoterapia', 'https://i.postimg.cc/rRWYV9bP/Curso-de-Massoterapia.png'),
('Curso de Farmácia Hospitalar', 3, 'farmacia-hospitalar', 'https://i.postimg.cc/w3SSC1Pr/Curso-de-Farm-cia-Hospitalar.png'),
('Curso de Auxiliar de Odontologia', 3, 'auxiliar-de-odontologia', 'https://i.postimg.cc/cg5NgTF1/Curso-de-Auxiliar-de-Odontologia.png'),
('Curso de Gerenciamento de Resíduos em Saúde', 3, 'gerenciamento-de-residuos-em-saude', 'https://i.postimg.cc/4KNM6V7Y/Curso-de-Gerenciamento-de-Res-duos-em-Sa-de.png'),
('Curso de Nutrição Básica', 3, 'nutricao-basica', 'https://i.postimg.cc/xqbZ30C3/Curso-de-Nutri-o-B-sica.png'),
('Curso de Desenho Artístico', 4, 'desenho-artistico', 'https://i.postimg.cc/rK4Ls1xc/Curso-de-Desenho-Art-stico.png'),
('Curso de Fotografia Digital', 4, 'fotografia-digital', 'https://i.postimg.cc/ppzgR2ML/Curso-de-Fotografia-Digital.png'),
('Curso de Design Gráfico', 4, 'design-grafico', 'https://i.postimg.cc/hXbWbK25/Curso-de-Design-Gr-fico.png'),
('Curso de Edição de Vídeo', 4, 'edicao-de-video', 'https://i.postimg.cc/94m3LsSF/Curso-de-Edi-o-de-V-deo.png'),
('Curso de Escultura', 4, 'escultura', 'https://i.postimg.cc/vD1J2rP9/Curso-de-Escultura.png'),
('Curso de Ilustração Digital', 4, 'ilustracao-digital', 'https://i.postimg.cc/jwDF9ThK/Curso-de-Ilustra-o-Digital.png'),
('Curso de Animação 2D', 4, 'animacao-2d', 'https://i.postimg.cc/Z02SJ79V/Curso-de-Anima-o-2-D.png'),
('Curso de Pintura em Tela', 4, 'pintura-em-tela', 'https://i.postimg.cc/svY0bw5B/Curso-de-Pintura-em-Tela.png'),
('Curso de Pedagogia', 5, 'pedagogia', 'https://i.postimg.cc/TKTHxgct/Curso-de-Pedagogia.png'),
('Curso de Técnicas de Ensino', 5, 'tecnicas-de-ensino', 'https://i.postimg.cc/686zgw9S/Curso-de-T-cnicas-de-Ensino.png'),
('Curso de Psicologia da Educação', 5, 'psicologia-da-educacao', 'https://i.postimg.cc/R3DPw8xY/Curso-de-Psicologia-da-Educa-o.png'),
('Curso de Alfabetização e Letramento', 5, 'alfabetizacao-e-letramento', 'https://i.postimg.cc/62QXpFL1/Curso-de-Alfabetiza-o-e-Letramento.png'),
('Curso de Gestão Escolar', 5, 'gestao-escolar', 'https://i.postimg.cc/qNrW79pX/Curso-de-Gest-o-Escolar.png'),
('Curso de Didática', 5, 'didatica', 'https://i.postimg.cc/McdCNd20/Curso-de-Did-tica.png'),
('Curso Livre de Inglês', 5, 'livre-de-ingles', 'https://i.postimg.cc/qzxj1gdy/Curso-Livre-de-Ingl-s.png'),
('Curso de Educação Inclusiva', 5, 'educacao-inclusiva', 'https://i.postimg.cc/Q9C231h2/Curso-de-Educa-o-Inclusiva.png');



INSERT INTO TABELA_CURSO_INSTITUICAO (
  CURSO_ID,
  INSTITUICAO_ID
)
VALUES 
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 3),
(10, 3),
(11, 3),
(12, 3),
(13, 4),
(14, 4),
(15, 4),
(16, 4),
(17, 5),
(18, 5),
(19, 5),
(20, 5),
(21, 6),
(22, 6),
(23, 6),
(24, 6),
(25, 7),
(26, 7),
(27, 7),
(28, 7),
(29, 8),
(30, 8),
(31, 8),
(32, 8),
(33, 9),
(34, 9),
(35, 9),
(36, 9),
(37, 10),
(38, 10),
(39, 10),
(40, 10);