-- SQLite
INSERT INTO TABELA_INSTITUICAO (
    NOME_INSTITUICAO, TELEFONE, SITE, INSTITUICAO_SLUG, IMG_LOGO_URL, EMAIL,
    RUA, BAIRRO, NUM, COMPLEMENTO, CEP, CIDADE, UF
) VALUES
    ('Escola de Tecnologia Digital TecnoAvanço', '34999456789', 'www.webwizardschool.com.br/', 'escola-tecnoavanco', 'https://i.postimg.cc/QtLZyXkW/Escola-de-Tecnologia-Digital-Tecno-Avan-o.png', 'info@tecdigital.com', 'Rua das Tecnologias', 'Jardim Europa', 123, NULL, 38400001,'Uberlândia', 'MG'),
    ('Instituto de Ciência da Computação FuturoTech', '34999912456', 'www.cybersafeinstitute.com.br', 'instituto-futurotech', 'https://i.postimg.cc/mkBfT8nL/Instituto-de-Ci-ncia-da-Computa-o-Futuro-Tech.png', 'contato@cienciadofuturo.com', 'Rua da Segurança Cibernética', 'Jardim California', 456, NULL, 38400002,'Uberlândia', 'MG'),
    ('Faculdade de Gestão Empresarial AdministraBrasil', '34999987654', 'www.administracaototalinstitute.com.br', 'faculdade-administrabrasil', 'https://i.postimg.cc/2yGpynp4/Faculdade-de-Gest-o-Empresarial-Administra-Brasil.png', 'atendimento@administracaototal.com', 'Avenida da Administração', 'Jardim Das Acácias', 789, NULL, 38400003,'Uberlândia', 'MG'),
    ('Escola de Administração Executiva Empreendeli', '34998461247', 'www.marketedgeacademy.com.br', 'escola-empreendeli', 'https://i.postimg.cc/FRjXt2DC/Escola-de-Administra-o-Executiva-Empreendeli.png', 'suporte@admexecutiva.com', 'Rua do Marketing', 'Jardim Holanda', 567, NULL, 38400004,'Uberlândia', 'MG'),
    ('Centro de Saúde Integrada SaúdeVital', '34999781234', 'www.medilearninstitute.com.br', 'centro-saudevital', 'https://i.postimg.cc/JhHWxyJL/Centro-de-Sa-de-Integrada-Sa-de-Vital.png', 'contato@saudevital.com', 'Rua da Medicina', 'Jardim Brasília', 321, NULL, 38400005, 'Uberlândia', 'MG'),
    ('Instituto de Medicina Avançada VidaSaudável', '34991235678', 'www.medicalproschool.com.br', 'instituto-vidasaudavel', 'https://i.postimg.cc/YSWJg5K2/Instituto-de-Medicina-Avan-ada-Vida-Saud-vel.png', 'atendimento@medicinaavancada.com', 'Avenida dos Profissionais de Saúde', 'Jardim Karaiba', 234, NULL, 38400006,'Uberlândia', 'MG'),
    ('Escola de Criatividade e Expressão Visual', '34997842525', 'www.criatividadevisual.com.br', 'escola-criatividadevisual', 'https://i.postimg.cc/J47VgYJK/Escola-de-Criatividade-e-Express-o-Visual.png', 'contato@criatividadevisual.com', 'Rua da Expressão Artística', 'Brasil ', 789, NULL, 38400007,'Uberlândia', 'MG'),
    ('Instituto de Arte e Design Brasil', '34992358788', 'www.artedesignbrasil.com.br', 'instituto-artedesignbrasil', 'https://i.postimg.cc/VL7Qc9Ww/Instituto-de-Arte-e-Design-Brasil.png', 'info@artedesignbrasil.com', 'Avenida das Artes', 'Uberlândia', 654, NULL, 38400008,'Aclimação', 'MG'),
    ('Instituto de Educação Pedagógica Brasil', '34993299174', 'www.educacaopedagogicabrasil.com.br', 'instituto-educacaopedagogicabrasil', 'https://i.postimg.cc/W1KBd2yf/Instituto-de-Educa-o-Pedag-gica-Brasil.png', 'atendimento@pedagogicabrasil.com', 'Rua da Educação', 'Ipanema', 987, NULL, 3840009,'Uberlândia', 'MG'),
    ('Escola de Formação de Educadores Avançados', '34991257456', 'www.formacaoeducadoresavancados.com.br', 'escola-formacaoeducadoresavancados', 'https://i.postimg.cc/PfQnSnLP/Escola-de-Forma-o-de-Educadores-Avan-ados.png', 'contato@formacaoeducadores.com', 'Avenida da Formação Pedagógica', 'Cidade Jardim', 543, NULL, 38400010,'Uberlândia', 'MG');

INSERT INTO TABELA_CATEGORIA_CURSO (
  NOME_CATEGORIA,
  IMG_URL,
  CATEGORIA_SLUG
)
VALUES
('Tecnologia da Informação', 'https://www.mackenzie.br/fileadmin/ARQUIVOS/Public/6-pos-graduacao/upm-higienopolis/EAD/Gest%C3%A3o_de_Tecnologia_da_Informa%C3%A7%C3%A3o/AdobeStock_487098177_Gest%C3%A3o_de_Tecnologia_da_Informa%C3%A7%C3%A3o.jpeg', 'tecnologia-da-informacao'),
('Negócios e Administração', 'https://t42748.vteximg.com.br/arquivos/ids/179131-1920-1280/administracao-de-conflitos-no-mundo-dos-negocios.jpg?v=637879737282830000', 'negocios-e-administracao'),
('Saúde e Medicina', 'https://global-uploads.webflow.com/5f7c5ad0f02de81be2e6417c/62ab6a97e4e49e6f2145da6a_medicina-preventiva.jpg', 'saude-e-medicina'), 
('Artes e Design', 'https://img.imageboss.me/revista-cdn/cdn/24714/f5aa11d17b3cffdd1af691e255d3310a39e22990.jpg?1572985641', 'artes-e-design'),
('Educação', 'https://smastr16.blob.core.windows.net/cea/sites/7/2020/09/educacao.jpg', 'educacao');

INSERT INTO TABELA_CURSO (
  NOME,
  ID_CATEGORIA_CURSO,
  CURSO_SLUG,
  IMG_URL,
  DESCRICAO
)
VALUES 
('Técnico em Desenvolvimento de Software', 1, 'desenvolvimento-de-software', 'https://i.postimg.cc/s2JNcHVq/T-cnico-em-Desenvolvimento-de-Software.png', 'Este curso é projetado para preparar os alunos para carreiras na área de desenvolvimento de software. Os estudantes aprendem linguagens de programação, como Java, Python ou C++, bem como os princípios de design de software, arquitetura de sistemas e metodologias de desenvolvimento ágil. Eles adquirem habilidades em resolução de problemas, depuração de código e desenvolvimento de aplicativos para diversas plataformas.'),
('Técnico em Suporte de Informática', 1, 'suporte-de-informatica', 'https://i.postimg.cc/Y9bTpnZY/T-cnico-em-Suporte-de-Inform-tica.png',' Este curso se concentra em capacitar os alunos a oferecer suporte técnico eficaz para sistemas de informática. Os tópicos incluem diagnóstico e resolução de problemas de hardware e software, configuração de redes, manutenção preventiva e atendimento ao cliente. Os alunos também aprendem sobre as últimas tecnologias e tendências em suporte de TI.'),
('Curso de Programação Web', 1, 'programacao-web', 'https://i.postimg.cc/mr30n2Sd/Curso-de-Programa-o-Web.png', 'Neste curso, os alunos mergulham no mundo do desenvolvimento web. Eles aprendem a criar sites interativos e aplicativos web usando linguagens como HTML, CSS e JavaScript, além de frameworks populares. O currículo também abrange design responsivo, usabilidade e otimização para mecanismos de busca.'),
('Curso de Segurança da Informação', 1, 'seguranca-da-informacao', 'https://i.postimg.cc/MKcgSYDf/Curso-de-Seguran-a-da-Informa-o.png', 'Os estudantes deste curso exploram a segurança cibernética em profundidade. Eles aprendem a identificar vulnerabilidades, implementar medidas de proteção, realizar testes de penetração e desenvolver políticas de segurança robustas. Tópicos adicionais incluem criptografia, gestão de incidentes de segurança e conformidade regulatória.'),
('Curso de Análise de Dados', 1, 'analise-de-dados', 'https://i.postimg.cc/W3L1G31X/Curso-de-Analise-de-Dados.png','Este curso se concentra em habilidades essenciais para analisar dados de forma eficaz. Os alunos aprendem a coletar, limpar e transformar dados, aplicar técnicas estatísticas e usar ferramentas como Python ou R para criar visualizações significativas. A ênfase está na tomada de decisões baseadas em dados.'),
('Curso de Design de Interface de Usuário', 1, 'design-de-interface-de-usuario', 'https://i.postimg.cc/8kbzvTQm/Curso-de-Design-de-Interface-de-Usu-rio.png', 'Os estudantes deste curso aprofundam-se no design de interfaces digitais. Eles exploram princípios de usabilidade, design centrado no usuário e criação de wireframes e protótipos. O currículo abrange também ferramentas de design gráfico e técnicas de animação.'),
('Curso de Administração de Banco de Dados', 1, 'administracao-de-banco-de-dados', 'https://i.postimg.cc/GpspTYd4/Curso-de-Administra-o-de-Banco-de-Dados.png','Neste curso, os alunos aprendem a projetar, implementar e administrar sistemas de gerenciamento de banco de dados (DBMS). Eles ganham competências em modelagem de dados, linguagem SQL, otimização de consultas e segurança de dados.'),
('Curso de Redes de Computadores', 1, 'redes-de-computadores', 'https://i.postimg.cc/2j9gMt4f/Curso-de-Redes-de-Computadores.png','Este curso explora a configuração e manutenção de redes de computadores. Os alunos aprendem sobre protocolos de rede, roteamento, segurança de rede, virtualização e administração de servidores.'),
('Técnico em Administração de Empresas', 2, 'administracao-de-empresas', 'https://i.postimg.cc/Jh8FjCWj/T-cnico-em-Administra-o-de-Empresas.png','Prepara os alunos para carreiras de gestão empresarial. Eles estudam aspectos como planejamento estratégico, gestão de recursos humanos, finanças corporativas, marketing e operações empresariais.'),
('Técnico em Gestão Financeira', 2, 'gestao-financeira', 'https://i.postimg.cc/ZR7Dk9vL/T-cnico-em-Gest-o-Financeira.png','Este curso se concentra na gestão eficaz das finanças corporativas. Os alunos aprendem sobre análise financeira, orçamentação, investimentos e gestão de riscos financeiros.'),
('Curso de Marketing Digital', 2, 'marketing-digital', 'https://i.postimg.cc/MKvJGwWT/Curso-de-Marketing-Digital.png','Os estudantes deste curso exploram estratégias de marketing online, incluindo publicidade em mídias sociais, SEO, marketing de conteúdo e análise de dados para otimização de campanhas.'),
('Curso de Gestão de Projetos', 2, 'gestao-de-projetos', 'https://i.postimg.cc/R0rB8Yx0/Curso-de-Gest-o-de-Projetos.png', 'Neste curso, os alunos aprendem as melhores práticas para planejar, executar e monitorar projetos de forma eficaz. Eles estudam metodologias como o PMBOK, Agile e Scrum, além de ferramentas de gerenciamento de projetos.'),
('Curso de Recursos Humanos', 2, 'recursos-humanos', 'https://i.postimg.cc/fyypk7QF/Curso-de-Recursos-Humanos.png', 'Prepara os alunos para funções relacionadas à gestão de pessoas em empresas. Os tópicos incluem recrutamento, seleção, treinamento, avaliação de desempenho e resolução de conflitos.'),
('Curso de Empreendedorismo', 2, 'empreendorismo', 'https://i.postimg.cc/D0fF6bkd/Curso-de-Empreendedorismo.png', 'Este curso ensina os princípios do empreendedorismo, desde a concepção de uma ideia de negócio até o planejamento estratégico, a gestão financeira e o marketing para startups e pequenas empresas.'),
('Curso de Logística Empresarial', 2, 'logistica-empresarial', 'https://i.postimg.cc/hvGWTWT2/Curso-de-Log-stica-Empresarial.png', 'Os alunos aprendem a otimizar a cadeia de suprimentos, abordando aspectos como gestão de estoque, distribuição, transporte e logística reversa.'),
('Curso de Contabilidade Básica', 2, 'cotabilidade-basica', 'https://i.postimg.cc/XqxN6kcz/Curso-de-Contabilidade-B-sica.png', 'Este curso introduz os conceitos contábeis fundamentais, preparando os alunos para registrar transações financeiras, criar demonstrativos contábeis e analisar a saúde financeira de uma organização.'),
('Técnico em Enfermagem', 3, 'enfermagem', 'https://i.postimg.cc/k4XhhNG4/T-cnico-em-Enfermagem.png', 'Prepara os alunos para trabalhar como auxiliares de enfermagem em hospitais e clínicas. Eles adquirem conhecimento em cuidados de saúde, administração de medicamentos e suporte a pacientes.'),
('Técnico em Radiologia', 3, 'radiologia', 'https://i.postimg.cc/FzYCh9jX/T-cnico-em-Radiologia.png', 'Este curso treina profissionais para operar equipamentos de radiologia e realizar exames de imagem médica com precisão.'),
('Curso de Primeiros Socorros', 3, 'primeiros-socorros' , 'https://i.postimg.cc/SKbBVzc2/Curso-de-Primeiros-Socorros.png', 'Os alunos aprendem técnicas de primeiros socorros para oferecer assistência imediata em situações de emergência, como acidentes e lesões.'),
('Curso de Massoterapia', 3, 'massoterapia', 'https://i.postimg.cc/qqZfGbG4/Curso-de-Massoterapia.png', 'Explora terapias de massagem terapêutica, incluindo técnicas de relaxamento e alívio da dor muscular.'),
('Curso de Farmácia Hospitalar', 3, 'farmacia-hospitalar', 'https://i.postimg.cc/RVF4nfTv/Curso-de-Farm-cia-Hospitalar.png', 'Prepara os alunos para trabalhar em farmácias de hospitais, garantindo a distribuição segura de medicamentos e o controle de estoque.'),
('Curso de Auxiliar de Odontologia', 3, 'auxiliar-de-odontologia', 'https://i.postimg.cc/NFQGnzTX/Curso-de-Auxiliar-de-Odontologia.png', 'Os estudantes aprendem a auxiliar dentistas em procedimentos odontológicos, esterilizar instrumentos e fornecer informações aos pacientes sobre higiene bucal.'),
('Curso de Gerenciamento de Resíduos em Saúde', 3, 'gerenciamento-de-residuos-em-saude', 'https://i.postimg.cc/FKj4QxhV/Curso-de-Gerenciamento-de-Res-duos-em-Sa-de.png', 'Este curso aborda o manejo seguro e regulamentado de resíduos médicos em ambientes de saúde, focando na prevenção de riscos e na proteção ambiental.'),
('Curso de Nutrição Básica', 3, 'nutricao-basica', 'https://i.postimg.cc/v8PdMTwk/Curso-de-Nutri-o-B-sica.png', 'Explora os princípios da nutrição e dieta, ensinando os alunos a promover hábitos alimentares saudáveis.'),
('Curso de Desenho Artístico', 4, 'desenho-artistico', 'https://i.postimg.cc/Gh73MzpB/Curso-de-Desenho-Art-stico.png', 'Este curso ensina técnicas avançadas de desenho, incluindo estudos de anatomia, luz e sombra, e perspectiva.'),
('Curso de Fotografia Digital', 4, 'fotografia-digital', 'https://i.postimg.cc/ncPZKzdB/Curso-de-Fotografia-Digital.png', 'Os alunos aprendem a capturar imagens de alta qualidade, dominando a exposição, composição, edição e uso de equipamentos fotográficos.'),
('Curso de Design Gráfico', 4, 'design-grafico', 'https://i.postimg.cc/13bmStws/Curso-de-Design-Gr-fico.png', ' Prepara os alunos para criar elementos gráficos atraentes e eficazes para impressão e mídia digital, abordando conceitos de tipografia, cores e identidade visual.'),
('Curso de Edição de Vídeo', 4, 'edicao-de-video', 'https://i.postimg.cc/N0TgjckT/Curso-de-Edi-o-de-V-deo.png', ' Explora técnicas de edição de vídeo avançadas, incluindo efeitos visuais, correção de cores e finalização de projetos audiovisuais.'),
('Curso de Escultura', 4, 'escultura', 'https://i.postimg.cc/HW3Tx3XS/Curso-de-Escultura.png','Os estudantes exploram a criação de esculturas tridimensionais em diversos materiais, como argila, madeira e metal.'),
('Curso de Ilustração Digital', 4, 'ilustracao-digital', 'https://i.postimg.cc/RFdxWV63/Curso-de-Ilustra-o-Digital.png', 'Este curso ensina a criar ilustrações digitais usando software especializado, abordando desde ilustrações vetoriais até pintura digital.'),
('Curso de Animação 2D', 4, 'animacao-2d', 'https://i.postimg.cc/Nfff7ZQq/Curso-de-Anima-o-2-D.png', 'Os alunos aprendem a criar animações bidimensionais, desenvolvendo personagens e enredos, além de técnicas de movimento e sincronização de áudio.'),
('Curso de Pintura em Tela', 4, 'pintura-em-tela', 'https://i.postimg.cc/bNWcD5JR/Curso-de-Pintura-em-Tela.png', 'Este curso explora técnicas de pintura em tela com ênfase em diferentes estilos artísticos, desde o realismo até a abstração.'),
('Curso de Pedagogia', 5, 'pedagogia', 'https://i.postimg.cc/zGhmnkHY/Curso-de-Pedagogia.png', ' Prepara os alunos para atuar como educadores, fornecendo conhecimento sobre teorias de aprendizado, práticas pedagógicas, e desenvolvimento de currículos.'),
('Curso de Técnicas de Ensino', 5, 'tecnicas-de-ensino', 'https://i.postimg.cc/52LGHNDx/Curso-de-T-cnicas-de-Ensino.png', 'Explora estratégias eficazes de ensino, métodos de avaliação, planejamento de aulas e uso de tecnologia na educação.'),
('Curso de Psicologia da Educação', 5, 'psicologia-da-educacao', 'https://i.postimg.cc/xC0WVDx9/Curso-de-Psicologia-da-Educa-o.png', 'Aborda a psicologia aplicada à educação, incluindo teorias de desenvolvimento humano, aprendizado, motivação e psicologia escolar.'),
('Curso de Alfabetização e Letramento', 5, 'alfabetizacao-e-letramento', 'https://i.postimg.cc/1tG5JQgP/Curso-de-Alfabetiza-o-e-Letramento.png', 'Prepara os alunos para auxiliar no processo de alfabetização, ensinando técnicas de leitura e escrita para crianças e adultos.'),
('Curso de Gestão Escolar', 5, 'gestao-escolar', 'https://i.postimg.cc/RZJmgB88/Curso-de-Gest-o-Escolar.png', 'Explora aspectos da gestão de instituições educacionais, incluindo liderança, administração de recursos e desenvolvimento de políticas educacionais.'),
('Curso de Didática', 5, 'didatica', 'https://i.postimg.cc/RFBv3DgY/Curso-de-Did-tica.png', 'Este curso aprofunda o entendimento de estratégias de ensino, métodos de avaliação e adaptação do currículo para atender às necessidades dos alunos.'),
('Curso Livre de Inglês', 5, 'livre-de-ingles', 'https://i.postimg.cc/rFv3Ftnn/Curso-Livre-de-Ingl-s.png', 'Focado no ensino do idioma inglês, cobrindo gramática, vocabulário, conversação e compreensão auditiva. Este curso é adequado para iniciantes e estudantes intermediários.'),
('Curso de Educação Inclusiva', 5, 'educacao-inclusiva', 'https://i.postimg.cc/1trsDrT3/Curso-de-Educa-o-Inclusiva.png', 'Os alunos aprendem a criar ambientes educacionais que atendam às necessidades de todos os alunos, incluindo aqueles com deficiências ou necessidades especiais. O currículo inclui adaptações curriculares e estratégias de ensino diferenciadas.');

INSERT INTO TABELA_CURSO_INSTITUICAO (
  CURSO_ID,
  INSTITUICAO_ID
)
VALUES 
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 3),
(10, 3),
(11, 3),
(12, 3),
(13, 4),
(14, 4),
(15, 4),
(16, 4),
(17, 5),
(18, 5),
(19, 5),
(20, 5),
(21, 6),
(22, 6),
(23, 6),
(24, 6),
(25, 7),
(26, 7),
(27, 7),
(28, 7),
(29, 8),
(30, 8),
(31, 8),
(32, 8),
(33, 9),
(34, 9),
(35, 9),
(36, 9),
(37, 10),
(38, 10),
(39, 10),
(40, 10);