-- SQLite

-- SELECT
--   C.*,
--   CC.NOME_CATEGORIA,
--   CC.CATEGORIA_SLUG
-- FROM
--   TABELA_CURSO C
-- INNER JOIN
--   TABELA_CURSO_INSTITUICAO CI ON C.ID = CI.CURSO_ID
-- INNER JOIN
--   TABELA_INSTITUICAO I ON CI.INSTITUICAO_ID = I.ID
-- INNER JOIN
--   TABELA_CATEGORIA_CURSO CC ON C.ID_CATEGORIA_CURSO = CC.ID
-- WHERE
--   I.ID = 4;

-- SELECT * FROM TABELA_INSTITUICAO;
-- SELECT * FROM TABELA_CATEGORIA_CURSO;
-- SELECT * FROM TABELA_CURSO_INSTITUICAO;
-- SELECT * FROM TABELA_CURSO;


-- SELECT
--   *
-- FROM
--   TABELA_CURSO
-- WHERE NOME LIKE '%téc%';

 SELECT
  TC.id AS curso_id,
  TC.nome AS nome_curso,
  TC.id_categoria_curso,
  TCC.nome_categoria,
  TCC.categoria_slug,
  TC.curso_slug,
  TC.img_url,
  TC.descricao,
  TEI.INSTITUICAO_ID,
  TI.NOME_INSTITUICAO,
  TI.RUA AS RUA_INSTITUICAO,
  TI.BAIRRO AS BAIRRO_INSTITUICAO,
  TI.NUM AS NUM_INSTITUICAO,
  TI.COMPLEMENTO AS COMPLEMENTO_INSTITUICAO,
  TI.CIDADE AS CIDADE_INSTITUICAO,
  TI.UF AS UF_INSTITUICAO
FROM
  TABELA_CURSO TC
INNER JOIN
  TABELA_CATEGORIA_CURSO TCC
ON TC.id_categoria_curso = TCC.id
LEFT JOIN
  TABELA_CURSO_INSTITUICAO TEI
ON TC.id = TEI.CURSO_ID
LEFT JOIN
  TABELA_INSTITUICAO TI
ON TEI.INSTITUICAO_ID = TI.ID
WHERE
  TC.id = 4